### ISSUE TITLE
Copyright violation concerns

### ISSUE THREAD

**Issue by jovrtn** [McDo/Momentum-Flickr#1]
Hello! I'm a co-founder of Momentum Dashboard. This project looks like a really awesome addition to the Momentum feature set, and we're supportive of the spirit of experimentation and tinkering of web technology. However, our code is not open source and posting it to a public GitHub repository is a violation of our copyright. We'd really appreciate if you would make this repository private, or remove it from GitHub entirely if a private repo is not possible. We'll also be contacting all forks of this project with the same request.

Thank you!

**Comment by McDo** [comment]
Hi @jovrtn 
Didn't mean to violate the copyright and apologize for that. The repo is just for helping the fans like me to custom Momentum for our own needs, I've received emails about how to implement this or that from guys with their cool ideas, which sounds really great to me. Definitely I will remove the code later but still want to maintain a README file about the hacking instructions, hope to have your understanding.

**Comment by jovrtn** [comment]
While it's awesome to see the high level of interest in Momentum to prompt this kind of customization, we don't currently condone unauthorized modifications to the code for either public or private use. Even so, our development roadmap includes offering approved methods and APIs by which Momentum can be extended and customized far beyond what is currently available, but for the time being we'd appreciate it if the repo was closed entirely instead of leaving a README file instructing others on how to continue making unauthorized modifications to our copyrighted source code. Thanks again!

**Comment by jovrtn** [comment]
Thank you for clearing the repo in your most recent commit, however the entirety of our code is still readily available in this repo's commit history. As I recommended initially, we'll need the repo to be made private or deleted entirely. Take care.
